# Generated by Django 5.1 on 2024-08-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructors'},
        ),
    ]
