# Generated by Django 5.1 on 2024-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0002_alter_instructor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='social_links',
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='ig',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
